### ISSUE TITLE
Не касается верстки. Контент

### ISSUE THREAD

**Issue by arpkirill** [LLC-WebSoft/web-soft-landing#10]
Данный issues требует обсуждения.
Шапка: предлагаю оставить следующие пункты в ней:

> 
1.  Главная
2.  Услуги
3. Контакты
4.  Обсудить проект 

все эти кнопки будут вызывать popup, в дальнейшем обновить на актуальные разделы.

УТП: Пропущены пробелы между словами.

Интеграции: 

> 
Общий текст:
1. Популярные CRM и ERP системы:
2. Платежные системы :
3. Сервисы рассылок :
4. Службы доставок:

Футер
Информация о ООО ??? 
(c) Web-soft или WEB-SOFT  ???  
Телефон ???
Почта ???

**Comment by DanilSord** [comment]
> > Какой popup?
> 
> который на бриф, у нас он один

согласен

**Comment by arpkirill** [comment]
89994695631

**Comment by cbrgpl** [comment]
> Шапка: предлагаю оставить следующие пункты в ней:
> 
> > 
> 
>     1. Главная
> 
>     2. Услуги
> 
>     3. Контакты
> 
>     4. Обсудить проект
> 
> 
> все эти кнопки будут вызывать popup, в дальнейшем обновить на актуальные разделы.

Не согласен, выглядит глупо.
Лучше явно отображать информацию о том, что это в скоре будет добавлено.
