### ISSUE TITLE
Карточки услуг не были исправлены.

### ISSUE THREAD

**Issue by arpkirill** [LLC-WebSoft/web-soft-landing#19]
https://github.com/LLC-WebSoft/web-soft-landing/issues/7 тут все написано про тень карточек, у на дизайне там есть легкая серая обводка карточек, а в макете их не
![Безымянный](https://user-images.githubusercontent.com/44532033/138881270-d9e225b8-fd2e-4445-8f54-6c7dfdde4ce1.png)
т.

**Comment by cbrgpl** [comment]
На моем мониторе не видно, нужно проверить, что все хорошо видно

**Comment by arpkirill** [comment]
> На моем мониторе не видно, нужно проверить, что все хорошо видно

проверю

**Comment by arpkirill** [comment]
![Безымянный](https://user-images.githubusercontent.com/44532033/139817274-775174e6-fd21-4a99-ba4d-6fe1b7d8e388.png)
Зеленое верно, но где красное не должна быть тень (ее там нет на макете)
