### ISSUE TITLE
Механика работы popup

### ISSUE THREAD

**Issue by arpkirill** [LLC-WebSoft/web-soft-landing#20]
В целом нужно вдохновиться https://braind.agency/#brief
Напишите несколько слов о вашей задаче - Высота изначально 1 row если текст не влазит, то высота должна меняться.
cursor: pointer для услуг и откуда вы о нас узнали.
![image](https://user-images.githubusercontent.com/44532033/138883397-f4a103db-4b86-4ea9-b229-18e80e50dbf5.png)
Убрать сложную валидацию данных.

1.  Обязательные поля: Напишите несколько слов о вашей задаче, Название компании, Имя, Телефон
2. Отключить везде валидацию данных, кроме телефона
3. Телефон это type="tel" и хорошая маска как у braind.agency
![image](https://user-images.githubusercontent.com/44532033/138884169-ec0eeca0-dbe6-426d-84e0-e0d4037fa7e2.png)
от 1053пх до 1625пх

**Comment by cbrgpl** [comment]
> 
> 
> /#brief тоже был бы не лишним

Игра не стоит свеч. Выглядит как фича ради фичи, нужно прилагать слишком много усилий для  реализации, учитывая реальную необходимость в ней.
