### ISSUE TITLE
плывет верстка шапки в сафари

### ISSUE THREAD

**Issue by arpkirill** [LLC-WebSoft/web-soft-landing#38]
![vIxEh6CBRBU.jpg](https://user-images.githubusercontent.com/44532033/140323481-15d69ea9-7fb4-47f2-98c3-95e862db7cce.jpg)

**Comment by cbrgpl** [comment]
Плывет не верстка, а space-картинка. `object-fit: fill` не работает. Нужно с помощью юзер агента определять браузер, если это сафари, ставить на картинку `object-fit: cover`
