### ISSUE TITLE
Images Lazy Loading && Images sizes

### ISSUE THREAD

**Issue by cbrgpl** [LLC-WebSoft/web-soft-landing#43]
Lazy loading работает хорошо, используется новая экспериментальная фича и полифил для нее для браузеров, к/е не поддерживают ее. Однако встает проблема в скорости подгрузки, картинки, которые подгружаются очень большие `600-800KB`, дистанция с которой начнется подгрузка не настраивается, каждый браузер определяет ее сам, поэтому при недостаточно высокой скорости интернета картинка появляется буквально на ходу. 

Думаю нужно вместо `SVG-картинкок` использовать `WEBP-картинки`, которые будут весить меньше, при этом качество картинок, очевидно, будет уже не такое высокое

**Comment by arpkirill** [comment]
А для браузеров, которые не поддерживают WEBP оставить svg?

**Comment by arpkirill** [comment]
Можем сжать все же еще картинки на сайте немного?

**Comment by cbrgpl** [comment]
> А для браузеров, которые не поддерживают WEBP оставить svg?

Da можно

**Comment by cbrgpl** [comment]
> Можем сжать все же еще картинки на сайте немного?

Svg уже некуда

**Comment by arpkirill** [comment]
> > Можем сжать все же еще картинки на сайте немного?
> 
> Svg уже некуда 

png, jpg

**Comment by cbrgpl** [comment]
> > > Можем сжать все же еще картинки на сайте немного?
> > 
> > Svg уже некуда 
> 
> png, jpg, webp

Это и так уже сжимается

**Comment by cbrgpl** [comment]
Обнаружилось, что использование больших SVG картинок приводит к очень-очень большому времени рендеринга - вплоть до 4-5сек от одной `700KB` картинки. Использование больших svg теперь недопустимо
